# Generated by Django 3.2.7 on 2023-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20220211_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.FloatField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='facedata',
            options={'ordering': ['user']},
        ),
    ]
